MA-16983 fix build error for vpu_wapper
Duplicate the imx_defaults from imx_android_mm to remove the deps
between vpu_wapper and imx_android_mm and fix below build error:
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l
out/.module_paths/Android.bp.list -b out/soong -n out -d
out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja
-o out/soong/build.ninja Android.bp
error: vendor/nxp-opensource/vpu_wrapper/Android.bp:61:1:
"lib_vpu_wrapper" depends on undefined module "imx_defaults"

Change-Id: I8f783788cef31f18efb6f9a4f65d3215ebf13848
Signed-off-by: Haoran.Wang <elven.wang@nxp.com>